import { SLOT_LABELS, SLOT_WEIGHTS } from "./core.js";

export const ROLE_LABELS = {
  tank: "坦克",
  healer: "治疗",
  dps: "输出",
};

export const PERSONALITIES = [
  {
    id: "steady",
    name: "稳重",
    benefit: "成功率贡献 +8%",
    drawback: "副本耗时贡献 +8%",
  },
  {
    id: "impatient",
    name: "急躁",
    benefit: "副本耗时贡献 -8%",
    drawback: "成功率贡献 -8%",
  },
  {
    id: "diligent",
    name: "勤奋",
    benefit: "个人经验 +15%",
    drawback: "副本耗时贡献 +5%",
  },
  {
    id: "competitive",
    name: "好胜",
    benefit: "越级副本战力 +10%",
    drawback: "碾压低级副本战力 -5%",
  },
  {
    id: "sociable",
    name: "合群",
    benefit: "职业丰富时战力最高 +8%",
    drawback: "重复职业过多时战力 -5%",
  },
  {
    id: "clever",
    name: "机智",
    benefit: "降低越级战力惩罚",
    drawback: "个人经验 -10%",
  },
];

export const CLASS_DEFINITIONS = [
  {
    id: "warrior",
    name: "战士",
    armorType: "mail",
    races: ["人类", "矮人", "暗夜精灵", "侏儒", "兽人", "牛头人", "巨魔", "亡灵"],
    specs: [
      { id: "warrior_protection", name: "防护", role: "tank" },
      { id: "warrior_arms", name: "武器", role: "dps" },
      { id: "warrior_fury", name: "狂怒", role: "dps" },
    ],
  },
  {
    id: "paladin",
    name: "圣骑士",
    armorType: "mail",
    races: ["人类", "矮人"],
    specs: [
      { id: "paladin_protection", name: "防护", role: "tank" },
      { id: "paladin_holy", name: "神圣", role: "healer" },
      { id: "paladin_retribution", name: "惩戒", role: "dps" },
    ],
  },
  {
    id: "hunter",
    name: "猎人",
    armorType: "leather",
    races: ["矮人", "暗夜精灵", "兽人", "牛头人", "巨魔"],
    specs: [
      { id: "hunter_beast_mastery", name: "野兽控制", role: "dps" },
      { id: "hunter_marksmanship", name: "射击", role: "dps" },
      { id: "hunter_survival", name: "生存", role: "dps" },
    ],
  },
  {
    id: "rogue",
    name: "盗贼",
    armorType: "leather",
    races: ["人类", "矮人", "暗夜精灵", "侏儒", "兽人", "巨魔", "亡灵"],
    specs: [
      { id: "rogue_assassination", name: "刺杀", role: "dps" },
      { id: "rogue_combat", name: "战斗", role: "dps" },
      { id: "rogue_subtlety", name: "敏锐", role: "dps" },
    ],
  },
  {
    id: "priest",
    name: "牧师",
    armorType: "cloth",
    races: ["人类", "矮人", "暗夜精灵", "巨魔", "亡灵"],
    specs: [
      { id: "priest_discipline", name: "戒律", role: "healer" },
      { id: "priest_holy", name: "神圣", role: "healer" },
      { id: "priest_shadow", name: "暗影", role: "dps" },
    ],
  },
  {
    id: "shaman",
    name: "萨满祭司",
    armorType: "leather",
    races: ["兽人", "牛头人", "巨魔"],
    specs: [
      { id: "shaman_restoration", name: "恢复", role: "healer" },
      { id: "shaman_elemental", name: "元素", role: "dps" },
      { id: "shaman_enhancement", name: "增强", role: "dps" },
    ],
  },
  {
    id: "mage",
    name: "法师",
    armorType: "cloth",
    races: ["人类", "侏儒", "巨魔", "亡灵"],
    specs: [
      { id: "mage_arcane", name: "奥术", role: "dps" },
      { id: "mage_fire", name: "火焰", role: "dps" },
      { id: "mage_frost", name: "冰霜", role: "dps" },
    ],
  },
  {
    id: "warlock",
    name: "术士",
    armorType: "cloth",
    races: ["人类", "侏儒", "兽人", "亡灵"],
    specs: [
      { id: "warlock_affliction", name: "痛苦", role: "dps" },
      { id: "warlock_demonology", name: "恶魔学识", role: "dps" },
      { id: "warlock_destruction", name: "毁灭", role: "dps" },
    ],
  },
  {
    id: "druid",
    name: "德鲁伊",
    armorType: "leather",
    races: ["暗夜精灵", "牛头人"],
    specs: [
      { id: "druid_feral_tank", name: "野性（守护）", role: "tank" },
      { id: "druid_restoration", name: "恢复", role: "healer" },
      { id: "druid_balance", name: "平衡", role: "dps" },
      { id: "druid_feral_dps", name: "野性（猛攻）", role: "dps" },
    ],
  },
];

export const NAME_PARTS = {
  first: [
    "铁锤",
    "月影",
    "黑麦",
    "铜须",
    "灰烬",
    "雷蹄",
    "夜雨",
    "碎牙",
    "麦芽",
    "霜叶",
    "咕噜",
    "石锅",
    "红胡子",
    "风铃",
    "暗鳞",
    "大葱",
  ],
  second: [
    "队长",
    "学徒",
    "大师",
    "小队员",
    "不迷路",
    "今天不鸽",
    "只需一件",
    "最后一把",
    "真的会玩",
    "奶得住",
    "稳稳的",
    "先开怪",
    "看攻略了",
    "专业替补",
    "忘带炉石",
  ],
};

export const LOG_TEMPLATES = {
  start: [
    "{tank} 说路线很熟，然后坚定地走向了另一个方向。",
    "{healer} 要求大家慢一点。大家一致同意，然后继续往前冲。",
    "队伍检查了补给，并决定把缺少的部分归类为临场发挥。",
  ],
  wailing_caverns: [
    "{member} 表示自己认识路。十分钟后，队伍再次经过了同一棵蘑菇。",
    "{healer} 提醒大家别踩水。{tank} 已经带着三群迅猛龙游到了对岸。",
    "洞穴里传来一声哀嚎。队伍认真听了一会儿，确认是迷路的输出。",
  ],
  deadmines: [
    "{tank} 问矿井里为什么有这么多海盗。{member} 回答这是西部荒野的产业升级。",
    "伐木机开始冒烟，队伍一致决定把它登记为正常工作状态。",
    "大门缓缓打开。所有人都假装刚才没有人忘记带火药。",
  ],
  shadowfang_keep: [
    "城堡的门自己关上了。{member} 说这是为了提升副本沉浸感。",
    "狼人从黑暗里扑出，{healer} 熟练地把尖叫声归类为团队预警。",
    "{tank} 说楼梯很安全，然后从唯一一个没有护栏的位置掉了下去。",
  ],
  oggleflint: [
    "奥格弗林特试图展示气势，但队伍正在讨论晚饭吃什么。",
    "{member} 率先冲了上去，战术说明随后才赶到。",
    "小怪数量比预期多。{tank} 坚称这属于额外收益。",
  ],
  taragaman_the_hungerer: [
    "塔拉加曼确实很饿，但看起来对法师面包并不满意。",
    "{healer} 的蓝量见底，{tank} 的血量也见底。双方都说问题不大。",
    "Boss 还剩 1%，所有输出同时开始研究伤害统计。",
  ],
  jergosh_the_invoker: [
    "耶戈什开始施法。队伍开始讨论刚才是谁负责打断。",
    "{member} 用一种没人看懂的方法避开了危险，并声称这都是计划的一部分。",
    "治疗压力突然增加，队伍决定用更大的嗓门弥补。",
  ],
  bazzalan: [
    "最终 Boss 就在眼前。刚才沉默的成员纷纷开始发表战术意见。",
    "巴扎兰倒下了，队伍迅速从战斗团队转型为装备委员会。",
    "装备出现的一瞬间，所有人的网络状况都奇迹般地恢复了。",
  ],
  failure: [
    "队伍一致认定这是一次战术性灭团，主要用于收集情报。",
    "大家讨论了失败原因，最后决定把锅交给不在场的人。",
    "{tank} 问治疗在哪里，{healer} 问坦克去了哪里。",
    "本次行动没有失败，只是提前结束并附带了一些经验教训。",
  ],
};

const ACTUAL_ITEMS = [
  {
    id: 14145,
    name: "被诅咒的魔刃",
    englishName: "Cursed Felblade",
    iconName: "inv_weapon_shortblade_12",
    quality: "uncommon",
    itemLevel: 18,
    slot: "mainHand",
    armorType: null,
    allowedClasses: ["warrior", "paladin", "hunter", "rogue"],
    allowedRoles: ["dps"],
    description: "原始属性将在完整物品库阶段导入；战斗效果只使用物品等级。",
  },
  {
    id: 14148,
    name: "水晶腕轮",
    englishName: "Crystalline Cuffs",
    iconName: "inv_bracer_13",
    quality: "uncommon",
    itemLevel: 18,
    slot: "wrist",
    armorType: "cloth",
    allowedClasses: ["mage", "priest", "warlock"],
    allowedRoles: ["healer", "dps"],
    description: "原始属性将在完整物品库阶段导入；战斗效果只使用物品等级。",
  },
  {
    id: 14149,
    name: "地下斗篷",
    englishName: "Subterranean Cape",
    iconName: "inv_misc_cape_18",
    quality: "uncommon",
    itemLevel: 18,
    slot: "back",
    armorType: null,
    allowedClasses: [],
    allowedRoles: [],
    description: "通用披风。原始属性仅展示，不进入战斗公式。",
  },
  {
    id: 14151,
    name: "咏唱之刃",
    englishName: "Chanting Blade",
    iconName: "inv_weapon_shortblade_25",
    quality: "uncommon",
    itemLevel: 18,
    slot: "mainHand",
    armorType: null,
    allowedClasses: ["paladin", "priest", "shaman", "druid"],
    allowedRoles: ["healer", "dps"],
    description: "原始属性将在完整物品库阶段导入；战斗效果只使用物品等级。",
  },
  {
    id: 14150,
    name: "唤魔者长袍",
    englishName: "Robe of Evocation",
    iconName: "inv_chest_cloth_24",
    quality: "uncommon",
    itemLevel: 18,
    slot: "chest",
    armorType: "cloth",
    allowedClasses: ["mage", "priest", "warlock"],
    allowedRoles: ["healer", "dps"],
    description: "原始属性将在完整物品库阶段导入；战斗效果只使用物品等级。",
  },
  {
    id: 14147,
    name: "洞穴护腕",
    englishName: "Cavedweller Bracers",
    iconName: "inv_bracer_07",
    quality: "uncommon",
    itemLevel: 18,
    slot: "wrist",
    armorType: "mail",
    allowedClasses: ["warrior", "paladin"],
    allowedRoles: ["tank", "dps"],
    description: "原始属性将在完整物品库阶段导入；战斗效果只使用物品等级。",
  },
];

const RAGEFIRE_QUEST_REWARD_ITEMS = [
  {
    id: 15452,
    name: "羽珠护腕",
    englishName: "Featherbead Bracers",
    iconName: "inv_bracer_08",
    quality: "uncommon",
    itemLevel: 18,
    slot: "wrist",
    armorType: "cloth",
    allowedClasses: ["mage", "priest", "warlock"],
    allowedRoles: ["healer", "dps"],
    description: "怒焰裂谷任务奖励。原始属性仅展示，战斗效果只使用物品等级。",
  },
  {
    id: 15453,
    name: "草原狮护腕",
    englishName: "Savannah Bracers",
    iconName: "inv_bracer_07",
    quality: "uncommon",
    itemLevel: 18,
    slot: "wrist",
    armorType: "leather",
    allowedClasses: ["hunter", "rogue", "shaman", "druid"],
    allowedRoles: ["tank", "healer", "dps"],
    description: "怒焰裂谷任务奖励。原始属性仅展示，战斗效果只使用物品等级。",
  },
  {
    id: 15449,
    name: "苍白长裤",
    englishName: "Ghastly Trousers",
    iconName: "inv_pants_14",
    quality: "uncommon",
    itemLevel: 18,
    slot: "legs",
    armorType: "cloth",
    allowedClasses: ["mage", "priest", "warlock"],
    allowedRoles: ["healer", "dps"],
    description: "怒焰裂谷任务奖励。原始属性仅展示，战斗效果只使用物品等级。",
  },
  {
    id: 15450,
    name: "泥泞护腿",
    englishName: "Dredgemire Leggings",
    iconName: "inv_pants_07",
    quality: "uncommon",
    itemLevel: 18,
    slot: "legs",
    armorType: "leather",
    allowedClasses: ["hunter", "rogue", "shaman", "druid"],
    allowedRoles: ["tank", "healer", "dps"],
    description: "怒焰裂谷任务奖励。原始属性仅展示，战斗效果只使用物品等级。",
  },
  {
    id: 15451,
    name: "石像鬼护腿",
    englishName: "Gargoyle Leggings",
    iconName: "inv_pants_03",
    quality: "uncommon",
    itemLevel: 18,
    slot: "legs",
    armorType: "mail",
    allowedClasses: ["warrior", "paladin"],
    allowedRoles: ["tank", "dps"],
    description: "怒焰裂谷任务奖励。原始属性仅展示，战斗效果只使用物品等级。",
  },
];

const EARLY_DUNGEON_ITEMS = [
  {
    id: 10412,
    name: "尖牙腰带",
    englishName: "Belt of the Fang",
    iconName: "inv_belt_30",
    quality: "uncommon",
    itemLevel: 21,
    slot: "waist",
    armorType: "leather",
    allowedClasses: ["hunter", "rogue", "shaman", "druid"],
    allowedRoles: ["tank", "healer", "dps"],
    description: "安娜科德拉的掉落。原始属性仅展示，战斗效果只使用物品等级。",
  },
  {
    id: 6460,
    name: "考布莱恩的腰带",
    englishName: "Cobrahn's Grasp",
    iconName: "inv_belt_03",
    quality: "rare",
    itemLevel: 24,
    slot: "waist",
    armorType: "mail",
    allowedClasses: ["warrior", "paladin"],
    allowedRoles: ["tank", "healer", "dps"],
    description: "考布莱恩领主的掉落。原始属性仅展示，战斗效果只使用物品等级。",
  },
  {
    id: 13245,
    name: "克雷什之背",
    englishName: "Kresh's Back",
    iconName: "inv_shield_18",
    quality: "rare",
    itemLevel: 20,
    slot: "offHand",
    armorType: null,
    allowedClasses: ["warrior", "paladin", "shaman"],
    allowedRoles: ["tank", "healer", "dps"],
    description: "克雷什的盾牌。原始属性仅展示，战斗效果只使用物品等级。",
  },
  {
    id: 6472,
    name: "毒蛇之刺",
    englishName: "Stinging Viper",
    iconName: "inv_wand_10",
    quality: "rare",
    itemLevel: 24,
    slot: "mainHand",
    armorType: null,
    allowedClasses: ["warrior", "paladin", "priest", "shaman", "druid"],
    allowedRoles: ["healer", "dps"],
    description: "皮萨斯领主的单手锤。原始属性仅展示，战斗效果只使用物品等级。",
  },
  {
    id: 6449,
    name: "发光的蜥蜴披风",
    englishName: "Glowing Lizardscale Cloak",
    iconName: "inv_chest_cloth_15",
    quality: "rare",
    itemLevel: 22,
    slot: "back",
    armorType: null,
    allowedClasses: [],
    allowedRoles: [],
    description: "斯卡姆的掉落。通用披风，战斗效果只使用物品等级。",
  },
  {
    id: 6469,
    name: "毒蛇",
    englishName: "Venomstrike",
    iconName: "inv_weapon_bow_10",
    quality: "rare",
    itemLevel: 24,
    slot: "ranged",
    armorType: null,
    allowedClasses: ["warrior", "hunter", "rogue"],
    allowedRoles: ["dps"],
    description: "瑟芬迪斯领主的弓。原始属性仅展示，战斗效果只使用物品等级。",
  },
  {
    id: 6631,
    name: "生命之根",
    englishName: "Living Root",
    iconName: "inv_staff_25",
    quality: "rare",
    itemLevel: 25,
    slot: "mainHand",
    twoHanded: true,
    armorType: null,
    allowedClasses: ["hunter", "priest", "shaman", "mage", "warlock", "druid"],
    allowedRoles: ["healer", "dps"],
    description: "永生者沃尔丹的法杖。双手武器统一占用主手栏位。",
  },
  {
    id: 6627,
    name: "穆坦努斯的胸甲",
    englishName: "Mutant Scale Breastplate",
    iconName: "inv_chest_plate08",
    quality: "rare",
    itemLevel: 28,
    slot: "chest",
    armorType: "mail",
    allowedClasses: ["warrior", "paladin"],
    allowedRoles: ["tank", "healer", "dps"],
    description: "吞噬者穆坦努斯的掉落。战斗效果只使用物品等级。",
  },
  {
    id: 5187,
    name: "拉克佐之锤",
    englishName: "Rhahk'Zor's Hammer",
    iconName: "inv_hammer_09",
    quality: "common",
    itemLevel: 20,
    slot: "mainHand",
    twoHanded: true,
    armorType: null,
    allowedClasses: ["warrior", "paladin", "shaman", "druid"],
    allowedRoles: ["dps"],
    description: "拉克佐的双手锤。双手武器统一占用主手栏位。",
  },
  {
    id: 5194,
    name: "工头战斧",
    englishName: "Taskmaster Axe",
    iconName: "inv_throwingaxe_06",
    quality: "rare",
    itemLevel: 23,
    slot: "mainHand",
    twoHanded: true,
    armorType: null,
    allowedClasses: ["warrior", "paladin", "hunter", "shaman"],
    allowedRoles: ["dps"],
    description: "斯尼德的双手斧。双手武器统一占用主手栏位。",
  },
  {
    id: 5199,
    name: "铁匠短裤",
    englishName: "Smelting Pants",
    iconName: "inv_pants_02",
    quality: "uncommon",
    itemLevel: 21,
    slot: "legs",
    armorType: "leather",
    allowedClasses: ["hunter", "rogue", "shaman", "druid"],
    allowedRoles: ["tank", "healer", "dps"],
    description: "基尔尼格的掉落。原始属性仅展示，战斗效果只使用物品等级。",
  },
  {
    id: 7230,
    name: "重拳先生的大锤",
    englishName: "Smite's Mighty Hammer",
    iconName: "inv_hammer_09",
    quality: "rare",
    itemLevel: 23,
    slot: "mainHand",
    twoHanded: true,
    armorType: null,
    allowedClasses: ["warrior", "paladin", "shaman", "druid"],
    allowedRoles: ["dps"],
    description: "重拳先生的双手锤。双手武器统一占用主手栏位。",
  },
  {
    id: 5201,
    name: "火石法杖",
    englishName: "Emberstone Staff",
    iconName: "inv_staff_13",
    quality: "rare",
    itemLevel: 23,
    slot: "mainHand",
    twoHanded: true,
    armorType: null,
    allowedClasses: ["hunter", "priest", "shaman", "mage", "warlock", "druid"],
    allowedRoles: ["healer", "dps"],
    description: "绿皮队长的法杖。双手武器统一占用主手栏位。",
  },
  {
    id: 5191,
    name: "残酷倒钩",
    englishName: "Cruel Barb",
    iconName: "inv_sword_24",
    quality: "rare",
    itemLevel: 24,
    slot: "mainHand",
    armorType: null,
    allowedClasses: ["warrior", "paladin", "hunter", "rogue", "mage", "warlock"],
    allowedRoles: ["dps"],
    description: "艾德温·范克里夫的单手剑。战斗效果只使用物品等级。",
  },
  {
    id: 5198,
    name: "曲奇的搅汤棒",
    englishName: "Cookie's Stirring Rod",
    iconName: "inv_staff_02",
    quality: "rare",
    itemLevel: 22,
    slot: "ranged",
    armorType: null,
    allowedClasses: ["priest", "mage", "warlock"],
    allowedRoles: ["healer", "dps"],
    description: "曲奇的魔杖。原始属性仅展示，战斗效果只使用物品等级。",
  },
  {
    id: 5254,
    name: "皱褶肩甲",
    englishName: "Rugged Spaulders",
    iconName: "inv_shoulder_08",
    quality: "common",
    itemLevel: 20,
    slot: "shoulder",
    armorType: "leather",
    allowedClasses: ["hunter", "rogue", "shaman", "druid"],
    allowedRoles: ["tank", "healer", "dps"],
    description: "雷希戈尔的掉落。原始属性仅展示，战斗效果只使用物品等级。",
  },
  {
    id: 1292,
    name: "屠夫的切肉刀",
    englishName: "Butcher's Cleaver",
    iconName: "inv_axe_23",
    quality: "rare",
    itemLevel: 25,
    slot: "mainHand",
    armorType: null,
    allowedClasses: ["warrior", "paladin", "hunter", "shaman"],
    allowedRoles: ["tank", "dps"],
    description: "屠夫拉佐克劳的单手斧。战斗效果只使用物品等级。",
  },
  {
    id: 6321,
    name: "席瓦莱恩家族徽记",
    englishName: "Silverlaine's Family Seal",
    iconName: "inv_belt_29",
    quality: "rare",
    itemLevel: 26,
    slot: "ring1",
    armorType: null,
    allowedClasses: [],
    allowedRoles: ["tank", "dps"],
    description: "席瓦莱恩男爵的戒指。战斗效果只使用物品等级。",
  },
  {
    id: 6320,
    name: "指挥官纹章盾",
    englishName: "Commander's Crest",
    iconName: "inv_shield_03",
    quality: "rare",
    itemLevel: 28,
    slot: "offHand",
    armorType: null,
    allowedClasses: ["warrior", "paladin", "shaman"],
    allowedRoles: ["tank", "healer"],
    description: "指挥官斯普林瓦尔的盾牌。战斗效果只使用物品等级。",
  },
  {
    id: 6318,
    name: "奥杜之杖",
    englishName: "Odo's Ley Staff",
    iconName: "inv_staff_27",
    quality: "rare",
    itemLevel: 26,
    slot: "mainHand",
    twoHanded: true,
    armorType: null,
    allowedClasses: ["hunter", "priest", "shaman", "mage", "warlock", "druid"],
    allowedRoles: ["healer", "dps"],
    description: "盲眼守卫奥杜的法杖。双手武器统一占用主手栏位。",
  },
  {
    id: 6340,
    name: "芬鲁斯的外皮",
    englishName: "Fenrus' Hide",
    iconName: "inv_misc_pelt_wolf_02",
    quality: "uncommon",
    itemLevel: 26,
    slot: "back",
    armorType: null,
    allowedClasses: [],
    allowedRoles: [],
    description: "吞噬者芬鲁斯的掉落。通用披风，战斗效果只使用物品等级。",
  },
  {
    id: 6314,
    name: "狼王斗篷",
    englishName: "Wolfmaster Cape",
    iconName: "inv_misc_cape_10",
    quality: "uncommon",
    itemLevel: 27,
    slot: "back",
    armorType: null,
    allowedClasses: [],
    allowedRoles: [],
    description: "狼王南杜斯的掉落。通用披风，战斗效果只使用物品等级。",
  },
  {
    id: 6324,
    name: "阿鲁高法袍",
    englishName: "Robes of Arugal",
    iconName: "inv_chest_cloth_31",
    quality: "rare",
    itemLevel: 29,
    slot: "chest",
    armorType: "cloth",
    allowedClasses: ["priest", "mage", "warlock"],
    allowedRoles: ["healer", "dps"],
    description: "大法师阿鲁高的掉落。原始属性仅展示，战斗效果只使用物品等级。",
  },
];

export const EQUIPMENT_SLOT_IDS = Object.keys(SLOT_WEIGHTS);
export { SLOT_LABELS };

export async function loadContent() {
  const [ragefireChasm, wailingCaverns, deadmines, shadowfangKeep, ...lootFiles] = await Promise.all([
    fetch("./data/dungeons/ragefire_chasm.json").then((response) => response.json()),
    fetch("./data/dungeons/wailing_caverns.json").then((response) => response.json()),
    fetch("./data/dungeons/deadmines.json").then((response) => response.json()),
    fetch("./data/dungeons/shadowfang_keep.json").then((response) => response.json()),
    fetch("./data/loot/ragefire_chasm.json").then((response) => response.json()),
    fetch("./data/loot/wailing_caverns.json").then((response) => response.json()),
    fetch("./data/loot/deadmines.json").then((response) => response.json()),
    fetch("./data/loot/shadowfang_keep.json").then((response) => response.json()),
  ]);

  const dungeons = [ragefireChasm, wailingCaverns, deadmines, shadowfangKeep];
  const items = [...ACTUAL_ITEMS, ...RAGEFIRE_QUEST_REWARD_ITEMS, ...EARLY_DUNGEON_ITEMS];
  const itemById = new Map(items.map((item) => [String(item.id), item]));
  const lootPools = new Map(
    lootFiles.flatMap((lootData) => lootData.pools).map((pool) => {
      return [pool.id, pool];
    }),
  );

  return {
    dungeon: ragefireChasm,
    dungeons,
    dungeonById: new Map(dungeons.map((dungeon) => [dungeon.id, dungeon])),
    lootPools,
    items,
    itemById,
    classes: CLASS_DEFINITIONS,
    personalities: PERSONALITIES,
  };
}

export function getClassDefinition(classId) {
  return CLASS_DEFINITIONS.find((entry) => entry.id === classId);
}

export function getSpecDefinition(specId) {
  for (const classDefinition of CLASS_DEFINITIONS) {
    const spec = classDefinition.specs.find((entry) => entry.id === specId);
    if (spec) return { ...spec, classId: classDefinition.id };
  }
  return undefined;
}

export function getPersonality(personalityId) {
  return PERSONALITIES.find((entry) => entry.id === personalityId);
}
